name: dynamic_properties
description: A mixin supporting map-based properties
homepage: https://github.com/iwauo/dart_dynamic_property
version: '1.0.0'
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  logging: ^0.11.4
dev_dependencies:
  test: '^1.12.0'
